title: Jacob Seifert, Ph.D.
description: |
  I am a postdoctoral researcher with a passion for optics, estimation theory, computational imaging, data science, machine learning, and deep learning.

  I enjoy the process of making sense of data and applying my skills to both research and engineering tasks â€“ always looking for new challenges and opportunities to learn new stuff.
theme: jekyll-theme-minimal
